# Generated by Django 5.0.8 on 2026-07-09 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('music', 'Music'), ('cultural', 'Cultural'), ('business', 'Business'), ('education', 'Education'), ('sports', 'Sports'), ('food', 'Food Festivals')], default='music', max_length=30)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
