# Generated by Django 6.0.7 on 2026-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_agenda_event_contact_email_event_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price_vip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
