# Generated by Django 6.0.6 on 2026-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('manage_users', models.BooleanField(default=False)),
                ('manage_events', models.BooleanField(default=False)),
                ('manage_organizers', models.BooleanField(default=False)),
                ('analytics', models.BooleanField(default=False)),
                ('reports', models.BooleanField(default=False)),
                ('delete_users', models.BooleanField(default=False)),
                ('delete_events', models.BooleanField(default=False)),
                ('notifications', models.BooleanField(default=False)),
            ],
        ),
    ]
